name: Gemini AI Code Reviewer (Org)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Gemini AI Code Reviewer
        uses: truongnh1992/gemini-ai-code-reviewer@v6.5.0
        with:
          google_api_key: ${{AIzaSyD7B2g-tcFip5dR5pxyQO0Yw__IbPnQB5w }}

