name: Gemini AI Code Reviewer (Org)

on:
  workflow_call:   # مهم جدًا مع Required Workflows

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Gemini AI Code Reviewer
        uses: truongnh1992/gemini-ai-code-reviewer@v6.5.0
        with:
          google_api_key: ${{ secrets.GOOGLE_API_KEY }}
