name: Gemini AI Code Reviewer (Org)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Gemini AI Code Reviewer
        uses: truongnh1992/gemini-ai-code-reviewer@v6.5.0
        with:
          # مطلوبان بواسطة الأكشن:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          # اختياري:
          # GEMINI_MODEL: "gemini-1.5-pro"  # أو اتركه على الافتراضي
          # INPUT_EXCLUDE: "dist/**,node_modules/**"  # لو عايز تستثني مسارات
